{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"high","kind":"identifier"}]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ADYWarningSeverity\/high"},"deprecationSummary":[{"inlineContent":[{"type":"text","text":"This will not be supported in future versions. Use WarningSeverity."}],"type":"paragraph"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/adyen3ds2_swift\/adywarningseverity\/high"]},{"paths":["\/documentation\/adyen3ds2_swift\/adywarningseverity\/high"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"Adyen3DS2_Swift"}],"symbolKind":"case","roleHeading":"Case","role":"symbol","externalID":"c:@M@Adyen3DS2_Swift@E@ADYWarningSeverity@ADYWarningSeverityHigh","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"high"}],"platforms":[],"title":"ADYWarningSeverity.high"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift","doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ADYWarningSeverity"]]},"references":{"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift":{"abstract":[],"identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift","url":"\/documentation\/adyen3ds2_swift","kind":"symbol","title":"Adyen3DS2_Swift","type":"topic","role":"collection"},"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift/ADYWarningSeverity":{"title":"ADYWarningSeverity","navigatorTitle":[{"kind":"identifier","text":"ADYWarningSeverity"}],"type":"topic","role":"symbol","url":"\/documentation\/adyen3ds2_swift\/adywarningseverity","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ADYWarningSeverity","kind":"identifier"}],"deprecated":true,"identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ADYWarningSeverity","kind":"symbol"},"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift/ADYWarningSeverity/high":{"type":"topic","url":"\/documentation\/adyen3ds2_swift\/adywarningseverity\/high","role":"symbol","abstract":[],"identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ADYWarningSeverity\/high","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"high"}],"deprecated":true,"title":"ADYWarningSeverity.high","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"ADYWarningSeverityHigh","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}}],"traits":[{"interfaceLanguage":"occ"}]}]}