{"relationshipsSections":[{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.adyen.Adyen3DS2-Swift\/SQ","doc:\/\/com.adyen.Adyen3DS2-Swift\/SH","doc:\/\/com.adyen.Adyen3DS2-Swift\/SY"],"type":"conformsTo"}],"deprecationSummary":[{"inlineContent":[{"text":"This will not be supported in future versions. Use WarningSeverity.","type":"text"}],"type":"paragraph"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ADYWarningSeverity","kind":"identifier"}],"title":"ADYWarningSeverity","externalID":"c:@M@Adyen3DS2_Swift@E@ADYWarningSeverity","navigatorTitle":[{"text":"ADYWarningSeverity","kind":"identifier"}],"role":"symbol","platforms":[],"roleHeading":"Enumeration","symbolKind":"enum","modules":[{"name":"Adyen3DS2_Swift"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ADYWarningSeverity","kind":"identifier"}],"languages":["swift"],"platforms":["Mac Catalyst"]}]}],"topicSections":[{"generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ADYWarningSeverity\/high","doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ADYWarningSeverity\/low","doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ADYWarningSeverity\/medium"],"anchor":"Enumeration-Cases"},{"title":"Initializers","identifiers":["doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ADYWarningSeverity\/init(rawValue:)"],"generated":true,"anchor":"Initializers"},{"anchor":"Default-Implementations","title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ADYWarningSeverity\/Equatable-Implementations","doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ADYWarningSeverity\/RawRepresentable-Implementations"]}],"variants":[{"paths":["\/documentation\/adyen3ds2_swift\/adywarningseverity"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/adyen3ds2_swift\/adywarningseverity"]}],"identifier":{"url":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ADYWarningSeverity","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift"]]},"references":{"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift/ADYWarningSeverity/low":{"role":"symbol","title":"ADYWarningSeverity.low","type":"topic","deprecated":true,"identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ADYWarningSeverity\/low","url":"\/documentation\/adyen3ds2_swift\/adywarningseverity\/low","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"low","kind":"identifier"}],"kind":"symbol","abstract":[]},"doc://com.adyen.Adyen3DS2-Swift/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/SQ","type":"unresolvable"},"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift":{"abstract":[],"identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift","url":"\/documentation\/adyen3ds2_swift","kind":"symbol","title":"Adyen3DS2_Swift","type":"topic","role":"collection"},"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift/ADYWarningSeverity/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ADYWarningSeverity\/RawRepresentable-Implementations","abstract":[],"type":"topic","url":"\/documentation\/adyen3ds2_swift\/adywarningseverity\/rawrepresentable-implementations","kind":"article","title":"RawRepresentable Implementations","role":"collectionGroup"},"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift/ADYWarningSeverity/medium":{"identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ADYWarningSeverity\/medium","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"medium","kind":"identifier"}],"title":"ADYWarningSeverity.medium","type":"topic","role":"symbol","deprecated":true,"abstract":[],"url":"\/documentation\/adyen3ds2_swift\/adywarningseverity\/medium","kind":"symbol"},"doc://com.adyen.Adyen3DS2-Swift/SH":{"type":"unresolvable","identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/SH","title":"Swift.Hashable"},"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift/ADYWarningSeverity/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","url":"\/documentation\/adyen3ds2_swift\/adywarningseverity\/equatable-implementations","identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ADYWarningSeverity\/Equatable-Implementations","type":"topic","abstract":[],"kind":"article"},"doc://com.adyen.Adyen3DS2-Swift/SY":{"type":"unresolvable","identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/SY","title":"Swift.RawRepresentable"},"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift/ADYWarningSeverity/high":{"type":"topic","url":"\/documentation\/adyen3ds2_swift\/adywarningseverity\/high","role":"symbol","abstract":[],"identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ADYWarningSeverity\/high","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"high"}],"deprecated":true,"title":"ADYWarningSeverity.high","kind":"symbol"},"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift/ADYWarningSeverity":{"title":"ADYWarningSeverity","navigatorTitle":[{"kind":"identifier","text":"ADYWarningSeverity"}],"type":"topic","role":"symbol","url":"\/documentation\/adyen3ds2_swift\/adywarningseverity","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ADYWarningSeverity","kind":"identifier"}],"deprecated":true,"identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ADYWarningSeverity","kind":"symbol"},"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift/ADYWarningSeverity/init(rawValue:)":{"identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ADYWarningSeverity\/init(rawValue:)","abstract":[],"type":"topic","title":"init(rawValue:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/adyen3ds2_swift\/adywarningseverity\/init(rawvalue:)","role":"symbol","deprecated":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":null,"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ADYWarningSeverity","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"}]}]}