{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"low"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift","doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ADYWarningSeverity"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/adyen3ds2_swift\/adywarningseverity\/low"]},{"paths":["\/documentation\/adyen3ds2_swift\/adywarningseverity\/low"],"traits":[{"interfaceLanguage":"occ"}]}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This will not be supported in future versions. Use WarningSeverity."}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ADYWarningSeverity\/low"},"metadata":{"role":"symbol","externalID":"c:@M@Adyen3DS2_Swift@E@ADYWarningSeverity@ADYWarningSeverityLow","modules":[{"name":"Adyen3DS2_Swift"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"low"}],"title":"ADYWarningSeverity.low","platforms":[],"symbolKind":"case","roleHeading":"Case"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","sections":[],"references":{"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift/ADYWarningSeverity/low":{"role":"symbol","title":"ADYWarningSeverity.low","type":"topic","deprecated":true,"identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ADYWarningSeverity\/low","url":"\/documentation\/adyen3ds2_swift\/adywarningseverity\/low","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"low","kind":"identifier"}],"kind":"symbol","abstract":[]},"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift":{"abstract":[],"identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift","url":"\/documentation\/adyen3ds2_swift","kind":"symbol","title":"Adyen3DS2_Swift","type":"topic","role":"collection"},"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift/ADYWarningSeverity":{"title":"ADYWarningSeverity","navigatorTitle":[{"kind":"identifier","text":"ADYWarningSeverity"}],"type":"topic","role":"symbol","url":"\/documentation\/adyen3ds2_swift\/adywarningseverity","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ADYWarningSeverity","kind":"identifier"}],"deprecated":true,"identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ADYWarningSeverity","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"ADYWarningSeverityLow","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"}]}]}