{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"medium","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/adyen3ds2_swift\/adywarningseverity\/medium"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/adyen3ds2_swift\/adywarningseverity\/medium"]}],"hierarchy":{"paths":[["doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift","doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ADYWarningSeverity"]]},"kind":"symbol","deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"This will not be supported in future versions. Use WarningSeverity.","type":"text"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"platforms":[],"modules":[{"name":"Adyen3DS2_Swift"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"medium","kind":"identifier"}],"title":"ADYWarningSeverity.medium","symbolKind":"case","role":"symbol","externalID":"c:@M@Adyen3DS2_Swift@E@ADYWarningSeverity@ADYWarningSeverityMedium"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ADYWarningSeverity\/medium"},"references":{"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift/ADYWarningSeverity":{"title":"ADYWarningSeverity","navigatorTitle":[{"kind":"identifier","text":"ADYWarningSeverity"}],"type":"topic","role":"symbol","url":"\/documentation\/adyen3ds2_swift\/adywarningseverity","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ADYWarningSeverity","kind":"identifier"}],"deprecated":true,"identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ADYWarningSeverity","kind":"symbol"},"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift/ADYWarningSeverity/medium":{"identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift\/ADYWarningSeverity\/medium","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"medium","kind":"identifier"}],"title":"ADYWarningSeverity.medium","type":"topic","role":"symbol","deprecated":true,"abstract":[],"url":"\/documentation\/adyen3ds2_swift\/adywarningseverity\/medium","kind":"symbol"},"doc://com.adyen.Adyen3DS2-Swift/documentation/Adyen3DS2_Swift":{"abstract":[],"identifier":"doc:\/\/com.adyen.Adyen3DS2-Swift\/documentation\/Adyen3DS2_Swift","url":"\/documentation\/adyen3ds2_swift","kind":"symbol","title":"Adyen3DS2_Swift","type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"ADYWarningSeverityMedium","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}